import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CdkTableModule } from '@angular/cdk/table';
import { MediaMatcher, LayoutModule } from '@angular/cdk/layout';
import { MatButtonModule, MatInputModule, MatCardModule, MatSelectModule,
         MatFormFieldModule, MatSidenavModule, MatToolbarModule, MatIconModule,
         MatListModule, MatAutocompleteModule, MatButtonToggleModule, MatCheckboxModule,
         MatChipsModule, MatDatepickerModule, MatDialogModule, MatDividerModule, MatExpansionModule,
         MatGridListModule, MatMenuModule, MatNativeDateModule, MatPaginatorModule, MatProgressBarModule,
         MatProgressSpinnerModule, MatRadioModule, MatRippleModule, MatSliderModule, MatSlideToggleModule,
         MatSnackBarModule, MatSortModule, MatStepperModule, MatTableModule, MatTabsModule, MatTooltipModule,
        } from '@angular/material';

@NgModule({
  imports: [
    CdkTableModule,
    LayoutModule,
    CommonModule,
    MatButtonModule,
    MatInputModule,
    MatCardModule,
    MatSelectModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatAutocompleteModule, 
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule, 
    MatDatepickerModule, 
    MatDialogModule, 
    MatDividerModule, 
    MatExpansionModule,
    MatGridListModule, 
    MatMenuModule, 
    MatNativeDateModule, 
    MatPaginatorModule, 
    MatProgressBarModule,
    MatProgressSpinnerModule, 
    MatRadioModule, 
    MatRippleModule, 
    MatSliderModule, 
    MatSlideToggleModule,
    MatSnackBarModule, 
    MatSortModule, 
    MatStepperModule,
    MatTableModule, 
    MatTabsModule, 
    MatTooltipModule,
  ],
  exports: [
    CdkTableModule,
    LayoutModule,
    MatButtonModule,
    MatInputModule,
    MatCardModule,
    MatSelectModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule, 
    MatDatepickerModule, 
    MatDialogModule, 
    MatDividerModule, 
    MatExpansionModule,
    MatGridListModule, 
    MatMenuModule, 
    MatNativeDateModule, 
    MatPaginatorModule, 
    MatProgressBarModule,
    MatProgressSpinnerModule, 
    MatRadioModule, 
    MatRippleModule, 
    MatSliderModule, 
    MatSlideToggleModule,
    MatSnackBarModule, 
    MatSortModule, 
    MatStepperModule,
    MatTableModule, 
    MatTabsModule, 
    MatTooltipModule,
  ],
  declarations: [],
  providers: [ MediaMatcher ]
})
export class MaterialModule { }
